apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-clalanne
spec:
  selector:
    matchLabels:
      app: payment-service-clalanne
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service-clalanne
    spec:
      containers:
      - name: payment-service-clalanne
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 200m
            memory: 300Mi
        image: us.gcr.io/"ID-PROJECT"/payment-service-clalanne:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "dev"
        livenessProbe:
          httpGet:
            path: /api/actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30     