apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-clalanne
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: payment-service-clalanne
            port:
              number: 80